blueprint:
  name: TRV Temperature Refresh
  description: Temperature Refresh for Zigbee valve TS0601, every n minute
  domain: automation
  input:
    valve:
      name: Smart Valve
      selector:
        entity:
          domain: climate
    period:
      name: Time period (minute)
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
  source_url: https://github.com/Se7ven/HassioBlueprints.git
variables:
  valve: !input valve
  period: !input period
trigger:
  - platform: time_pattern
    minutes: !input period
action:
  - service: mqtt.publish
    data_template:
      topic: "zigbee2mqtt/{{state_attr(valve,'friendly_name')}}/set/local_temperature_calibration"
      payload_template: "{{ state_attr(valve, 'local_temperature_calibration')|float(0) | round(1, 'half') }}"